# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-20 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchitem',
            name='url',
            field=models.URLField(),
        ),
    ]
